export const artistProfiles = [
  {
    id: 1,
    name: "Ananya Verma",
    gender: "Female",
    profileImgUrl: "https://i.pravatar.cc/150?img=1",
    location: "Indiranagar, Bangalore",
    category: "Saree Drapeer",
    bio: "A professional saree draper specializing in elegant bridal and occasion styling. Ananya is known for creating polished, comfortable drapes tailored to different saree fabrics and body types.",
    socialLinks: {
      instagram: "https://instagram.com/ananyaverma",
      facebook: "https://facebook.com/ananyaverma",
    },
    createdAt: "2026-08-20T10:00:00+05:30",
  },
  {
    id: 2,
    name: "Rohan Kapoor",
    gender: "Male",
    profileImgUrl: "https://i.pravatar.cc/150?img=2",
    location: "Bandra, Mumbai",
    category: "Makeup Artist",
    bio: "A creative makeup artist focused on bridal, fashion, and event looks. Rohan combines modern techniques with personalized styling to create clean and camera-ready finishes.",
    socialLinks: {
      instagram: "https://instagram.com/rohankapoor_makeup",
      facebook: "https://facebook.com/rohankapoor.makeup",
    },
    createdAt: "2026-08-21T11:30:00+05:30",
  },
  {
    id: 3,
    name: "Meera Joshi",
    gender: "Female",
    profileImgUrl: "https://i.pravatar.cc/150?img=3",
    location: "Ahmedabad, Gujarat",
    category: "Mehendi Artist",
    bio: "A mehendi artist specializing in intricate bridal designs, personalized motifs, and contemporary patterns. Meera is known for detailed linework and expressive traditional designs.",
    socialLinks: {
      instagram: "https://instagram.com/meerajoshi_mehendi",
      facebook: "https://facebook.com/meerajoshimehendi",
    },
    createdAt: "2026-08-22T09:15:00+05:30",
  },
  {
    id: 4,
    name: "Arjun Malhotra",
    gender: "Male",
    profileImgUrl: "https://i.pravatar.cc/150?img=4",
    location: "Pune, Maharashtra",
    category: "Photographer",
    bio: "A professional photographer specializing in weddings, portraits, and lifestyle events. Arjun focuses on natural expressions, storytelling compositions, and vibrant visual memories.",
    socialLinks: {
      instagram: "https://instagram.com/arjunmalhotra_photo",
      facebook: "https://facebook.com/arjunmalhotraphotography",
    },
    createdAt: "2026-08-23T14:45:00+05:30",
  },
  {
    id: 5,
    name: "Kiara Shah",
    gender: "Female",
    profileImgUrl: "https://i.pravatar.cc/150?img=5",
    location: "Mumbai, Maharashtra",
    category: "Musician",
    bio: "A versatile musician performing acoustic, contemporary, and Indian fusion music. Kiara brings a warm stage presence and a carefully curated setlist to private events and celebrations.",
    socialLinks: {
      instagram: "https://instagram.com/kiarashah_music",
      facebook: "https://facebook.com/kiarashahmusic",
    },
    createdAt: "2026-08-24T16:20:00+05:30",
  },
  {
    id: 6,
    name: "Vikram Singh",
    gender: "Male",
    profileImgUrl: "https://i.pravatar.cc/150?img=6",
    location: "Delhi, India",
    category: "Comedian",
    bio: "A stand-up comedian delivering observational humor and entertaining stories inspired by everyday Indian life. Vikram performs for corporate events, private gatherings, and comedy shows.",
    socialLinks: {
      instagram: "https://instagram.com/vikramsingh_comedy",
      facebook: "https://facebook.com/vikramsinghcomedy",
    },
    createdAt: "2026-08-25T12:10:00+05:30",
  },
  {
    id: 7,
    name: "Ishita Rao",
    gender: "Female",
    profileImgUrl: "https://i.pravatar.cc/150?img=7",
    location: "Bangalore, Karnataka",
    category: "Dancer",
    bio: "A trained dancer experienced in Bollywood, contemporary, and traditional Indian dance styles. Ishita performs at weddings, stage events, and cultural celebrations with energetic choreography.",
    socialLinks: {
      instagram: "https://instagram.com/ishitarao_dance",
      facebook: "https://facebook.com/ishitaraodance",
    },
    createdAt: "2026-08-26T13:40:00+05:30",
  },
  {
    id: 8,
    name: "Aditya Nair",
    gender: "Male",
    profileImgUrl: "https://i.pravatar.cc/150?img=8",
    location: "Kochi, Kerala",
    category: "Wall Artist",
    bio: "A mural and wall artist creating vibrant custom artwork for homes, cafes, offices, and public spaces. Aditya blends contemporary illustration with local cultural influences.",
    socialLinks: {
      instagram: "https://instagram.com/adityanair_art",
      facebook: "https://facebook.com/adityanairart",
    },
    createdAt: "2026-08-27T10:25:00+05:30",
  },
  {
    id: 9,
    name: "Pooja Desai",
    gender: "Female",
    profileImgUrl: "https://i.pravatar.cc/150?img=9",
    location: "Surat, Gujarat",
    category: "Makeup Artist",
    bio: "A beauty and makeup professional specializing in bridal makeup, party looks, and traditional Gujarati styling. Pooja focuses on long-lasting finishes that look natural both in person and in photographs.",
    socialLinks: {
      instagram: "https://instagram.com/poojadesai_beauty",
      facebook: "https://facebook.com/poojadesaibeauty",
    },
    createdAt: "2026-08-28T15:00:00+05:30",
  },
  {
    id: 10,
    name: "Karan Mehta",
    gender: "Male",
    profileImgUrl: "https://i.pravatar.cc/150?img=10",
    location: "Jaipur, Rajasthan",
    category: "Wall Artist",
    bio: "A creative wall artist known for detailed murals, decorative artwork, and custom theme-based paintings. Karan works with clients to transform blank spaces into visually engaging environments.",
    socialLinks: {
      instagram: "https://instagram.com/karanmehta_art",
      facebook: "https://facebook.com/karanmehtaart",
    },
    createdAt: "2026-08-29T11:45:00+05:30",
  },
];
