export const popularEvents = [
  {
    id: 1,
    title: "Hiring experienced Content Writers & Photographers",
    location: "Andheri West, Mumbai",
    budget: 5000,
    featureImage: "https://example.com/images/content-writer-1.jpg",
    startsAt: "2026-08-17T09:00:00+05:30",
    eventDescription:
      "We are looking for experienced content writers and photographers for an upcoming corporate event. The team will be responsible for creating engaging content and capturing high-quality photographs throughout the event.",
    thingsToKnow: {
      location: "Andheri West, Mumbai",
      date: "17th August - 19th August",
      time: "9:00 AM - 6:00 PM",
      budget: "₹5,000 (Fixed)",
    },
    user: {
      id: 101,
      name: "Rajesh Kumar",
      profileImage: "https://i.pravatar.cc/150?img=11",
    },
    gallery: [
      "https://example.com/gallery/1-1.jpg",
      "https://example.com/gallery/1-2.jpg",
      "https://example.com/gallery/1-3.jpg",
    ],
    createdAt: "2026-08-12T09:00:00+05:30",
  },
  {
    id: 2,
    title: "Urgent Need for Photographer & Videographer",
    location: "HSR Layout, Bangalore",
    budget: 5000,
    featureImage: "https://example.com/images/photographer-2.jpg",
    startsAt: "2026-08-17T17:00:00+05:30",
    eventDescription:
      "We need an experienced photographer and videographer to cover an upcoming event. The assignment includes event photography, video coverage, interviews, and capturing important moments for social media and promotional use.",
    thingsToKnow: {
      location: "HSR Layout, Bangalore",
      date: "17th August - 19th August",
      time: "5:00 PM - 10:00 PM",
      budget: "₹5,000 (Fixed)",
    },
    user: {
      id: 102,
      name: "Swarup Mehta",
      profileImage: "https://i.pravatar.cc/150?img=11",
    },
    gallery: [
      "https://example.com/gallery/2-1.jpg",
      "https://example.com/gallery/2-2.jpg",
      "https://example.com/gallery/2-3.jpg",
    ],
    createdAt: "2026-08-12T08:30:00+05:30",
  },
  {
    id: 3,
    title: "Wedding Photographer Required",
    location: "Koramangala, Bangalore",
    budget: 12000,
    featureImage: "https://example.com/images/wedding-3.jpg",
    startsAt: "2026-08-18T10:30:00+05:30",
    eventDescription:
      "Looking for a professional wedding photographer to capture candid moments, family portraits, ceremonies, and key highlights from the wedding celebration.",
    thingsToKnow: {
      location: "Koramangala, Bangalore",
      date: "18th August - 19th August",
      time: "10:30 AM - 10:00 PM",
      budget: "₹12,000 (Fixed)",
    },
    user: {
      id: 103,
      name: "Amit Sharma",
      profileImage: "https://i.pravatar.cc/150?img=11",
    },
    gallery: [
      "https://example.com/gallery/3-1.jpg",
      "https://example.com/gallery/3-2.jpg",
      "https://example.com/gallery/3-3.jpg",
    ],
    createdAt: "2026-08-11T14:20:00+05:30",
  },
  {
    id: 4,
    title: "Corporate Event Photographer Needed",
    location: "Bandra, Mumbai",
    budget: 7500,
    featureImage: "https://example.com/images/corporate-4.jpg",
    startsAt: "2026-08-21T08:00:00+05:30",
    eventDescription:
      "Professional photographer required for a corporate networking event. Coverage will include speakers, audience interactions, branding, group photographs, and candid moments.Professional photographer required for a corporate networking event. Coverage will include speakers, audience interactions, branding, group photographs, and candid moments.Professional photographer required for a corporate networking event. Coverage will include speakers, audience interactions, branding, group photographs, and candid moments.",
    thingsToKnow: {
      location: "Bandra, Mumbai",
      date: "21st August",
      time: "8:00 AM - 5:00 PM",
      budget: "₹7,500 (Fixed)",
    },
    user: {
      id: 104,
      name: "Neha Verma",
      profileImage: "https://i.pravatar.cc/150?img=11",
    },
    gallery: [
      "https://example.com/gallery/4-1.jpg",
      "https://example.com/gallery/4-2.jpg",
      "https://example.com/gallery/4-3.jpg",
    ],
    createdAt: "2026-08-11T11:45:00+05:30",
  },
  {
    id: 5,
    title: "Product Photographer for Brand Shoot",
    location: "Powai, Mumbai",
    budget: 8000,
    featureImage: "https://example.com/images/product-5.jpg",
    startsAt: "2026-08-22T11:00:00+05:30",
    eventDescription:
      "We are hiring a product photographer for a new product launch. The shoot requires clean studio-style images, lifestyle shots, and detailed product photographs suitable for e-commerce and social media.",
    thingsToKnow: {
      location: "Powai, Mumbai",
      date: "22nd August - 23rd August",
      time: "11:00 AM - 7:00 PM",
      budget: "₹8,000 (Fixed)",
    },
    user: {
      id: 105,
      name: "Karan Patel",
      profileImage: "https://i.pravatar.cc/150?img=11",
    },
    gallery: [
      "https://example.com/gallery/5-1.jpg",
      "https://example.com/gallery/5-2.jpg",
      "https://example.com/gallery/5-3.jpg",
    ],
    createdAt: "2026-08-10T16:10:00+05:30",
  },
  {
    id: 6,
    title: "Fashion Photographer Required",
    location: "Indiranagar, Bangalore",
    budget: 10000,
    featureImage: "https://example.com/images/fashion-6.jpg",
    startsAt: "2026-08-23T14:00:00+05:30",
    eventDescription:
      "Looking for a creative fashion photographer for a portfolio and campaign shoot. Candidates should have experience with studio lighting, outdoor portraits, and fashion photography.",
    thingsToKnow: {
      location: "Indiranagar, Bangalore",
      date: "23rd August",
      time: "2:00 PM - 8:00 PM",
      budget: "₹10,000 (Fixed)",
    },
    user: {
      id: 106,
      name: "Priya Nair",
      profileImage: "https://i.pravatar.cc/150?img=11",
    },
    gallery: [
      "https://example.com/gallery/6-1.jpg",
      "https://example.com/gallery/6-2.jpg",
      "https://example.com/gallery/6-3.jpg",
    ],
    createdAt: "2026-08-10T12:30:00+05:30",
  },
  {
    id: 7,
    title: "Videographer for Music Event",
    location: "Whitefield, Bangalore",
    budget: 9000,
    featureImage: "https://example.com/images/music-event-7.jpg",
    startsAt: "2026-08-26T18:00:00+05:30",
    eventDescription:
      "Experienced videographer required to cover a live music event. The work includes stage coverage, audience reactions, artist interviews, and short promotional clips.",
    thingsToKnow: {
      location: "Whitefield, Bangalore",
      date: "26th August",
      time: "6:00 PM - 11:00 PM",
      budget: "₹9,000 (Fixed)",
    },
    user: {
      id: 107,
      name: "Rohit Singh",
      profileImage: "https://i.pravatar.cc/150?img=11",
    },
    gallery: [
      "https://example.com/gallery/7-1.jpg",
      "https://example.com/gallery/7-2.jpg",
      "https://example.com/gallery/7-3.jpg",
    ],
    createdAt: "2026-08-09T18:40:00+05:30",
  },
  {
    id: 8,
    title: "Content Writer for Event Campaign",
    location: "Pune, Maharashtra",
    budget: 6000,
    featureImage: "https://example.com/images/content-8.jpg",
    startsAt: "2026-08-28T09:30:00+05:30",
    eventDescription:
      "We are looking for an experienced content writer to create event announcements, social media posts, email campaigns, and promotional copy for an upcoming event.",
    thingsToKnow: {
      location: "Pune, Maharashtra",
      date: "28th August - 30th August",
      time: "9:30 AM - 5:30 PM",
      budget: "₹6,000 (Fixed)",
    },
    user: {
      id: 108,
      name: "Anjali Deshmukh",
      profileImage: "https://i.pravatar.cc/150?img=11",
    },
    gallery: [
      "https://example.com/gallery/8-1.jpg",
      "https://example.com/gallery/8-2.jpg",
      "https://example.com/gallery/8-3.jpg",
    ],
    createdAt: "2026-08-09T10:15:00+05:30",
  },
  {
    id: 9,
    title: "Real Estate Photographer Needed",
    location: "Gurgaon, Haryana",
    budget: 4500,
    featureImage: "https://example.com/images/real-estate-9.jpg",
    startsAt: "2026-08-29T07:30:00+05:30",
    eventDescription:
      "Professional real estate photographer required to capture high-quality interior and exterior photographs of residential properties for online listings and marketing campaigns.",
    thingsToKnow: {
      location: "Gurgaon, Haryana",
      date: "29th August",
      time: "7:30 AM - 2:00 PM",
      budget: "₹4,500 (Fixed)",
    },
    user: {
      id: 109,
      name: "Vikram Joshi",
      profileImage: "https://i.pravatar.cc/150?img=11",
    },
    gallery: [
      "https://example.com/gallery/9-1.jpg",
      "https://example.com/gallery/9-2.jpg",
      "https://example.com/gallery/9-3.jpg",
    ],
    createdAt: "2026-08-08T15:25:00+05:30",
  },
  {
    id: 10,
    title: "Event Photographer & Social Media Creator",
    location: "Connaught Place, Delhi",
    budget: 7000,
    featureImage: "https://example.com/images/social-event-10.jpg",
    startsAt: "2026-08-31T16:00:00+05:30",
    eventDescription:
      "We are looking for a photographer and social media creator who can capture live event moments and create quick social media content including reels, stories, and photographs.",
    thingsToKnow: {
      location: "Connaught Place, Delhi",
      date: "31st August - 1st September",
      time: "4:00 PM - 10:00 PM",
      budget: "₹7,000 (Fixed)",
    },
    user: {
      id: 110,
      name: "Meera Kapoor",
      profileImage: "https://i.pravatar.cc/150?img=11",
    },
    gallery: [
      "https://example.com/gallery/10-1.jpg",
      "https://example.com/gallery/10-2.jpg",
      "https://example.com/gallery/10-3.jpg",
    ],
    createdAt: "2026-08-08T09:50:00+05:30",
  },
];
